---
title: "Testing similarity metrics"
author: "Richard J Beck"
date: "3/10/2023"
output: html_document
---

Various ways of establishing similarity between populations.

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="~/projects/008_birthrateLandscape/ALFA-K/")
```


```{r}
source("utils/landscape_functions.R")
source("utils/ALFA-K.R")
source("utils/comparison_functions.R")
library(ggplot2)
library(fields)
library(parallel)
```

```{r,include=F,eval=F}
source("figures/testing_similarity/eval_comparison_metrics.R") 
```

Example of angle metric

```{r}
x <- readRDS("figures/testing_similarity/metrics.Rds")
exclude <- grepl("0p1",x$test) | grepl("0p1",x$ref)
x <- x[!exclude,]
x$ident <- x$test==x$ref
p <- ggplot(x,aes(x=angle,fill=ident,group=ident))+
  geom_histogram(alpha=0.3,position = "identity",binwidth=15)+
  scale_fill_discrete("landscapes\ncompared",labels=c("different","identical"))+
  scale_x_continuous(breaks=seq(0,120,30))+
  theme_bw()
p
```

```{r}

x <- readRDS("figures/testing_similarity/metrics.Rds")
x$wl <- sapply(x$test,function(i){
  unlist(strsplit(i,split="_"))[4]
})
x$id <- "different"
x$id[x$test==x$ref] <- "identical"

z <- x

x <- reshape2::melt(x,measure.vars=c("ll","angle","dwass"))
x <- x[is.finite(x$value),]

p1 <- ggplot(x,aes(x=value,group=id,fill=id))+
  facet_wrap(variable~wl,scales="free",nrow=3)+
  geom_density()+
    theme(legend.position = "top")
p1

p2 <- ggplot(z,aes(x=angle,y=dwass,color=id))+
  facet_wrap(~wl)+
  geom_point()
p2

p2 <- ggplot(z,aes(x=angle,y=ll,color=id))+
  facet_wrap(~wl)+
  geom_point()
p2

```

```{r}
y <- split(x,f=interaction(x$variable,x$wl))
#yi <- y[[1]]
df <- do.call(rbind,lapply(y, function(yi){
  d <- sm.density.compare(x=yi$value,group=yi$id,display="none")
  
  res <- sum(d$estimate[1,]*d$estimate[2,])/sum(d$estimate[1,]*d$estimate[1,])
  
  #res <- ks.test(i,d)$p.value
  df <- yi[1,c("wl","variable")]
  df$res <- res
  return(df)
}))

p0 <- ggplot(df,aes(x=wl,y=variable,fill=res))+
  geom_raster()+
  scale_fill_viridis_c()
p0
```
