---
title: "landscape_visualisation"
author: "Richard J Beck"
date: "3/10/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="~/projects/008_birthrateLandscape/ALFA-K/")
```


```{r}

source("utils/ALFA-K.R")
library(ggplot2)
library(fields)
library(snifter)
library(mgcv)
```

Problems with this approach is that the 33333 karyotype is not in the right place and we plot landscape areas that we really have no right to. 
```{r}

x <- readRDS("bc_landscapes/hTERTa/nn_clones.Rds")
fit <- readRDS("bc_landscapes/hTERTa/krig.Rds")
xmat <- do.call(rbind,lapply(rownames(x), function(pki) as.numeric(unlist(strsplit(pki,split="[.]")))))
y <- x$f_est

d2 <- gen_all_neighbours(rownames(x))

z <- fitsne(xmat,simplified=FALSE)
z2 <- project(z,d2,xmat)

df <- data.frame(rbind(z,z2))
df$f <- c(y,predict(fit,d2))

p1 <- ggplot(df,aes(x=X1,y=X2,color=f))+
  geom_point(alpha=0.2,size=4)+
  scale_color_viridis_c()
p1

tmp <- akima::interp(df$X1,df$X2,df$f,duplicate="mean",nx=100,ny=100)
lvis <- tmp[[3]]
rownames(lvis)<-tmp$x
colnames(lvis)=tmp$y
tmp <- reshape2::melt(lvis)
colnames(tmp) <- c("X1","X2","f")

#d0 <- xmat[x$id=="frequent",]
z0 <- data.frame(z[x$id=="frequent",])
z0$id <- rownames(x)[x$id=="frequent"]

p <- ggplot(tmp,aes(x=X1,y=X2))+
  geom_raster(aes(fill=f))+
  geom_point(data=z0)+
  scale_fill_viridis_c()+
  ggrepel::geom_text_repel(data=z0,aes(label=id),size=2)
p
stop()
library(mgcv)
spl1 <- gam(f ~ s(X1, X2, bs = 'sos'), data = df)
# fine grid, coarser is faster
df2 <- data.frame(expand.grid(X1 = seq(min(df$X1),max(df$X1),length.out=100), X2=seq(min(df$X2),max(df$X2),length.out=100)))

df2$value <- predict(spl1, df2, type = "response")



p2 <- ggplot(df2,aes(x=X1,y=X2))+
  geom_raster(aes(fill=value))+
  geom_point(data=z0)+
  scale_fill_viridis_c()+
  ggrepel::geom_text_repel(data=z0,aes(label=id),size=2)
p2
```

```{r}
library(mclust)
library(MASS)
x <- readRDS("bc_landscapes/hTERTa/frequent_clones.Rds")
xmat <- do.call(rbind,lapply(rownames(x), function(pki) as.numeric(unlist(strsplit(pki,split="[.]")))))

fit <- mvn(modelName = "XXX",data=xmat)
xmat2 <- round(mvrnorm(n=100,mu=fit$parameters$mean,Sigma = fit$parameters$variance$Sigma))

xmat0 <- rbind(xmat,xmat2)
z <- fitsne(xmat0,simplified=FALSE)

x <- readRDS("bc_landscapes/hTERTa/nn_clones.Rds")
fit <- readRDS("bc_landscapes/hTERTa/krig.Rds")
xmat <- rbind(gen_all_neighbours(rownames(x)),
              do.call(rbind,lapply(rownames(x), function(pki){
                as.numeric(unlist(strsplit(pki,split="[.]")))
              })))
y <- predict(fit,xmat)

z2 <- project(z,xmat,xmat0)

df <- data.frame(z2)
df$f <- y


p1 <- ggplot(df,aes(x=X1,y=X2,color=f))+
  geom_point(alpha=0.2,size=4)+
  scale_color_viridis_c()
p1

library(mgcv)
#credit https://stackoverflow.com/questions/35019382
spl1 <- gam(f ~ s(X1, X2, bs = 'ds'), data = df)
# fine grid, coarser is faster
df2 <- data.frame(expand.grid(X1 = seq(min(df$X1),max(df$X1),length.out=100), X2=seq(min(df$X2),max(df$X2),length.out=100)))

df2$value <- predict(spl1, df2, type = "response")

x0 <- readRDS("bc_landscapes/hTERTa/frequent_clones.Rds")

d0 <- do.call(rbind,lapply(rownames(x0), function(pki) as.numeric(unlist(strsplit(pki,split="[.]")))))
z0 <- data.frame(project(z,d0,xmat0))
z0$id <- rownames(x0)

p2 <- ggplot(df2,aes(x=X1,y=X2))+
  geom_raster(aes(fill=value))+
  geom_point(data=z0)+
  scale_fill_viridis_c()+
  ggrepel::geom_text_repel(data=z0,aes(label=id),size=2)
p2
```
