---
title: "README"
author: "Richard J Beck"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---

Fitting ALFA-K model to Salehi data

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/projects/008_birthrateLandscape/ALFA-K/")
```

```{r}
library(ggplot2)
longest_cons <- function(ff,longest=T){
  ids <- sapply(ff, function(fi){
    fsplit <- unlist(strsplit(fi,split="_"))
    lsplit <- length(fsplit)
    fsplit <- fsplit[1:(lsplit-6)]
    paste(fsplit,collapse="_")
  })
  ff <- split(ff,f=ids)
  
  ff <- sapply(ff, function(fi){
    fi <- fi[order(fi)]
    if(longest) return(tail(fi,1))
    return(head(fi,1))
  })
  as.character(ff)
}
wrap_tree <- function(pdx_id,m){
  x <- m[m$PDX_id==pdx_id,]
  x$x <- as.numeric(gsub("X","",x$x))

  xseg <- x[!is.na(x$parent),]

  xseg <- cbind(xseg,do.call(rbind,lapply(xseg$parent, function(i){
    tmp <- x[x$uid==i,c("x","y")]
    colnames(tmp) <- paste0(colnames(tmp),"start")
    tmp
  })))
  list(x=x,xseg=xseg)
}

```

Lineage nomenclature

```{r}

m <- read.csv("data/salehi/metadata.csv")
m <- m[m$PDX_id=="SA609",]
if(FALSE){
root <- m$uid[is.na(m$parent)]
lineages <- list(list(id="",uids=root))
new_lineages <- list()
finished_lineages <- list()


while(length(lineages)>0){
  for(li in lineages){
  descendents <- m$uid[!is.na(m$parent)&m$parent==tail(li$uids,1)]
  if(length(descendents)==0) finished_lineages <- c(finished_lineages,li)
  new_lineages <- c(new_lineages,lapply(descendents, function(di) {
    lij <- li
    lij$uids <- c(lij$uids,di)
    if(length(descendents)>1) lij$id <- paste0(lij$id,letters[which(descendents==di)])
    return(lij)
    }))
}
lineages <- new_lineages
new_lineages <- list()
#print(lineages)
}
}
assign_labels <- function(m){
  root <- m$uid[is.na(m$parent)]
lineages <- list(c(x=root))
new_lineages <- list()
finished_lineages <- list()


while(length(lineages)>0){
  for(li in lineages){
  descendents <- m$uid[!is.na(m$parent)&m$parent==tail(li,1)]
  if(length(descendents)==0) finished_lineages <- c(finished_lineages,list(li))
  new_lineages <- c(new_lineages,lapply(descendents, function(di) {
    lij <- c(li,di)
    names(lij)[length(lij)] <- tail(names(li),1)
    if(length(descendents)>1){
      names(lij)[length(lij)] <- paste0(tail(names(li),1),letters[which(descendents==di)])
    }
    return(lij)
    }))
  }
lineages <- new_lineages
new_lineages <- list()

}

ids <- unlist(finished_lineages)
ids <- ids[!duplicated(ids)]
m <- m[order(m$uid),]
ids <- ids[order(ids)]
m$linlab <- names(ids)
m$linlab <- gsub("x","",m$linlab)
return(m)
}

adder <- function(xx,dx,dy){
  xx$x$x <- xx$x$x + dx
  xx$xseg$x <- xx$xseg$x + dx
  xx$xseg$xstart <- xx$xseg$xstart + dx
  xx$x$y <- xx$x$y + dy
  xx$xseg$y <- xx$xseg$y + dy
  xx$xseg$ystart <- xx$xseg$ystart + dy
  return(xx)
}

wrap_assign_labels <- function(m){
  m <- split(m,f=m$PDX_id)
  do.call(rbind,lapply(m,assign_labels))
}

```



```{r}



m <- read.csv("data/salehi/metadata.csv")
x <- readRDS("figures/salehi_data_fitting/fit_summaries.Rds")
x <- x[!x$has_parents&x$min_obs==5,]

m$r2 <- sapply(m$uid, function(i){
  if(!i%in%x$uid) return(NaN)
  x$r2[x$uid==i]
  })

m <- wrap_assign_labels(m)
saveRDS(m,"data/salehi/metadata.Rds")

x906 <- adder(wrap_tree("SA906",m),0,0)
x1035 <- adder(wrap_tree("SA1035",m),0,2)
x532 <- adder(wrap_tree("SA532",m),0,5)
x535 <- adder(wrap_tree("SA535",m),0,7)
x609 <- adder(wrap_tree("SA609",m),9,3)

linlabs <- data.frame(x=c(1,4,2,5,11),y=c(1,3.5,4.5,8,4),
                      labs=c("SA906","SA1035","SA532","SA535","SA609"))

x <- rbind(x906$x,x1035$x,x532$x,x535$x,x609$x)
xseg <- rbind(x906$xseg,x1035$xseg,x532$xseg,x535$xseg,x609$xseg)

p <- ggplot(x,aes(x=x,y=y))+
  geom_segment(data=xseg,aes(xend=xstart,yend=ystart,linetype=on_treatment),alpha=0.5)+
  geom_point(aes(color=r2),size=5)+
  geom_text(aes(label=linlab),nudge_y = 0.3,color="red")+
  geom_text(data=linlabs,aes(label=labs))+
  scale_color_viridis_c(expression(R^2),limits=c(-1,1))+
  scale_linetype_discrete("treatment",labels=c("on","off"))+
  theme_classic()+
  theme(axis.text = element_blank(),axis.title = element_blank(),
        axis.line = element_blank(),axis.ticks = element_blank(),legend.position = c(0.1,0.8),legend.key.size = unit(0.2,"in"))
p
ggsave("figures/salehi_data_fitting/figures/lineage_maps.png",width=9,height=7,units="in")
rownames(x) <- NULL
saveRDS(x,"figures/salehi_data_fitting/labelled_metadata.Rds")
```
Non Overlapping lineages.

```{r}



x <- readRDS("figures/salehi_data_fitting/fit_summaries_post_jump.Rds")
x <- x[x$r2>0.2&x$min_obs==5,]
x[,c("samples","treatment_status","filenames","id")]
```

```{r}
library(RColorBrewer)



ff <- c("SA609UnBU_X7_l_6_d1_0_d2_0.Rds",
        "SA609R2_X7_l_4_d1_0_d2_0.Rds",
        "SA609U1_X8_l_5_d1_0_d2_0.Rds",
"SA535_CISPLATIN_CombinedU_X9_l_5_d1_0_d2_0.Rds",
        "SA535_CISPLATIN_CombinedT_X10_l_6_d1_0_d2_0.Rds")
ids <- gsub(".Rds","",ff)
m <- readRDS("data/salehi/metadata.Rds")
lineages <- readRDS("figures/salehi_data_fitting/lineages.Rds")
lineages <- lineages[ids]

x535 <- adder(wrap_tree("SA535",m),0,8)
x609 <- adder(wrap_tree("SA609",m),0,0)

x <- rbind(x535$x,x609$x)
xseg <- rbind(x535$xseg,x609$xseg)

labpoints <- sapply(lineages, function(li) tail(li$ids,1))
xlab <- x[x$uid%in%labpoints,]

colpoint <- do.call(rbind,lapply(1:length(lineages),function(i){
  li <- lineages[[i]]
  ids <- li$ids
  msel <- x[x$uid%in%ids,]
  msel$lid <- letters[i]
  msel
}))

linlabs <- data.frame(x=c(1,4),y=c(2,9),labs=c("SA609","SA535"))

p <- ggplot(x,aes(x=x,y=y))+
  geom_segment(data=xseg,aes(xend=xstart,yend=ystart,linetype=on_treatment),show.legend = F)+
  geom_point(size=5)+
  geom_point(data=colpoint,aes(color=lid),size=5,show.legend = F)+
  geom_text(data=xlab,aes(label=linlab),nudge_y = 0.3,color="red")+
  geom_text(data=linlabs,aes(label=labs))+
 # scale_color_viridis_c(expression(R^2),limits=c(-1,1))+
  theme_classic()+
  theme(axis.text = element_blank(),axis.title = element_blank(),
        axis.line = element_blank(),axis.ticks = element_blank())+
  scale_color_brewer(palette="Set2")
p

ggsave("figures/salehi_data_fitting/figures_post_jump/lineage_maps_sel.png",width=5,height=7,units="in")
```


Ploidy variation within lineages

```{r}

ploidy_tree <- function(x){
  x$x$ploidy<- sapply(x$x$library_ids,function(i){
    i <- unlist(strsplit(i,split=";"))
    cni <- do.call(rbind,cn[i])
    mean(unlist(cni))
  })
  return(x)
}

m <- read.csv("data/salehi/metadata.csv")
lineages <- readRDS("figures/salehi_data_fitting/lineages.Rds")
cn <- readRDS("data/salehi/chrom_level_cn.Rds")

x535 <- wrap_tree("SA535",m)
x535 <- ploidy_tree(x535)
p <- ggplot(x535$x,aes(x=x,y=y))+
  geom_segment(data=x535$xseg,aes(xend=xstart,yend=ystart,linetype=on_treatment))+
  geom_point(aes(color=ploidy),size=5)+
  scale_color_viridis_c()+
  theme_classic()+
  theme(axis.text = element_blank(),axis.title = element_blank(),
        axis.line = element_blank(),axis.ticks = element_blank())+
  ggtitle("SA535")
p

x609 <- ploidy_tree(wrap_tree("SA609",m))

p <- ggplot(x609$x,aes(x=x,y=y))+
  geom_segment(data=x609$xseg,aes(xend=xstart,yend=ystart,linetype=on_treatment))+
  geom_point(aes(color=ploidy),size=5)+
  scale_color_viridis_c()+
  theme_classic()+
  theme(axis.text = element_blank(),axis.title = element_blank(),
        axis.line = element_blank(),axis.ticks = element_blank())+
  ggtitle("SA609")
p

x1035 <- ploidy_tree(wrap_tree("SA1035",m))
p <- ggplot(x1035$x,aes(x=x,y=y))+
  geom_segment(data=x1035$xseg,aes(xend=xstart,yend=ystart,linetype=on_treatment))+
  geom_point(aes(color=ploidy),size=5)+
  scale_color_viridis_c()+
  theme_classic()+
  theme(axis.text = element_blank(),axis.title = element_blank(),
        axis.line = element_blank(),axis.ticks = element_blank())+
  ggtitle("SA1035")
p

x532 <- ploidy_tree(wrap_tree("SA532",m))
p <- ggplot(x532$x,aes(x=x,y=y))+
  geom_segment(data=x532$xseg,aes(xend=xstart,yend=ystart,linetype=on_treatment))+
  geom_point(aes(color=ploidy),size=5)+
  scale_color_viridis_c()+
  theme_classic()+
  theme(axis.text = element_blank(),axis.title = element_blank(),
        axis.line = element_blank(),axis.ticks = element_blank())+
  ggtitle("SA532")
p
```