---
title: "README"
author: "Richard J Beck"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---

Fitting ALFA-K model to Salehi data

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/projects/008_birthrateLandscape/ALFA-K/")
```

```{r}
library(ggplot2)
source("utils/visualisation_functions.R")
get_best <- function(x){
  cx <- sapply(x, function(xi){
    if(is.null(xi)) return(-Inf)
    if("loo_pred"%in%colnames(xi$xv_res)){
      return(cor(xi$xv_res$f_est,xi$xv_res$loo_pred)*nrow(xi$xv_res))
    }
    if("f_xv"%in%colnames(xi$xv_res)){
      return(cor(xi$xv_res$f_est,xi$xv_res$f_xv)*nrow(xi$xv_res))
    }
    
  }) 
  return(x[[which.max(cx)]])
}
```
First source the following to prepare the sample data (the third one takes a few hours)
```{r,eval=F}

plotf <- function(fi,n){
  print(fi)
  data_obj <- readRDS(paste0("data/salehi/alfak_inputs/",fi))
  fit_obj <- get_best(readRDS(paste0("data/salehi/alfak_fits_minobs_adaptive/",fi)))
  if(is.null(fit_obj)) return(NULL)

  x <- melt_for_plotting(data_obj,nclones=n,fit_obj)
  id <- unlist(strsplit(fi,split=".Rds"))[1]
  p <- ggplot(x$data,aes(x=time,y=frequency,color=karyotype))+
  facet_wrap(~karyotype)+
  geom_point(size=2)+
  geom_line(data=x$fit)+
  theme_classic(base_size=12)+
    ggtitle(id)+
  scale_y_sqrt()
p
}

ff <- list.files("data/salehi/alfak_fits_minobs_adaptive/")

p <- lapply(ff,plotf,n=10)
p <- p[!sapply(p,is.null)]

lapply(p,plot)



```

