---
title: "ALFA-K method images"
author: "Richard J Beck"
date: "2023-11-21"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="~/projects/008_birthrateLandscape/ALFA-K/figures/alfak_demo_ims/")
```


```{r}
library(ggplot2)
x0 <- c(0,-8,-15,-5)
f <- c(0.3,0.5,0.6,0.45)
t <- seq(0,100,8)
df <- do.call(cbind,lapply(1:length(x0), function(i){
  exp(x0[i]+f[i]*t)
}))

df <- data.frame(t(apply(df,1, function(di) {
  dii <- di*rnorm(length(di),mean=1,sd=0.2)
  dii/sum(dii)
  })))
df$time <- t
df <- reshape2::melt(df,id.vars="time")

t <- seq(0,100,1)
df2 <- do.call(cbind,lapply(1:length(x0), function(i){
  exp(x0[i]+f[i]*t)
}))

df2 <- data.frame(t(apply(df2,1, function(dii) {
  dii/sum(dii)
  })))
df2$time <- t
df2 <- reshape2::melt(df2,id.vars="time")

p <- ggplot(df,aes(x=time,y=value,color=variable))+
  geom_point(size=2)+
  geom_line(data=df2)+
  scale_y_continuous("karyotype frequency")+
  scale_x_continuous("time (days)")+
  scale_color_discrete("karyotype\nID")+
  theme_classic(base_size=12)
p

ggsave("fq_fit.png",plot=p,width=4,height=2.5,units="in")


```

```{r}

library(plotly)
psize <- 10
set.seed(42)
pts <- data.frame(cbind(sample(1:psize,4),sample(1:psize,4)))
pts$f <- c(0.4,0.5,0.6,0.45)


df <- do.call(rbind,lapply(1:nrow(pts), function(i){
  nn <- rbind(pts[i,1:2]+c(1,0),
    pts[i,1:2]+c(0,1),
    pts[i,1:2]+c(-1,0),
    pts[i,1:2]+c(0,-1))
  nn$f <- pts$f[i]-rnorm(4,mean=0.2,sd=0.05)
  nn
}))

pts$id <- "obs"
df$id <- "nn"

df <- rbind(df,pts)

library(fields)

opt <- Krig(df[,1:2],df$f,m=1,df=20)
pred <- expand.grid(0:(1+psize),0:(1+psize))
colnames(pred) <- c("X1","X2")

#
pred$f <- predict(opt,pred)
pred$col <- 0

pred <- list(x=unique(pred$X1),y=unique(pred$X2),z=matrix(pred$f,nrow=length(unique(pred$X1)),byrow = TRUE),col=matrix(0,nrow=length(unique(pred$X1))))


#pred <- akima::interp(x=df$X2,y=df$X1,z = df$f,xo = seq(0,1+psize,0.5),yo=seq(0,1+psize,0.5),extrap=T)
#pred$col <- pred$z*0
#z <- matrix(pred$f,ncol=psize,byrow = TRUE)



fig <- plot_ly()
fig <- fig %>% add_trace(type="scatter3d",data=df, x = ~X1, y = ~X2, z = ~f, color = ~id, colors = c('#BF382A', "grey" ,'#0C4B8E'),showlegend=T)
fig <- fig %>% add_trace(type="surface",data=pred,x=~x,y=~y,z=~z,opacity=0.5,surfacecolor=~col,showlegend=F)
fig <- fig %>% layout(scene = list(xaxis = list(title = ''),
                     yaxis = list(title = ''),
                     zaxis = list(title = 'fitness'),
                     camera=list(eye = list(x=-1.5, y=1, z=0.64))))
fig


fig <- plot_ly()
fig <- fig %>% add_trace(type="scatter3d",data=df, x = ~X1, y = ~X2, z = ~f, color = ~id, colors = c('#BF382A' ,'#0C4B8E'),showlegend=T)
fig <- fig %>% layout(scene = list(xaxis = list(title = ''),
                     yaxis = list(title = ''),
                     zaxis = list(title = 'fitness'),
                     camera=list(eye = list(x=-1.5, y=1, z=0.64))))
fig
```

X validation:

```{r}
library(plotly)
psize <- 10
set.seed(4)
pts <- data.frame(cbind(sample(1:psize,20,replace=T),sample(1:psize,20,replace=T)))
pts <- unique(pts)
pk1 <- c(2,2)
pk2 <- c(7,8)
pts$f <- apply(pts,1,function(pki){
  max(1/(1+sqrt(sum((pki-pk1)^2))),1/(1+0.7*sqrt(sum((pki-pk2)^2))))
})

train <- pts[1:(nrow(pts)-1),]
tst <- pts[nrow(pts),]
train$id <- "train"
tst$id <- "test"

library(fields)

opt <- Krig(train[,1:2],train$f,m=1,df=nrow(pts)-3)
pred <- expand.grid(0:(1+psize),0:(1+psize))
colnames(pred) <- c("X1","X2")

#
pred$f <- predict(opt,pred)
pred$col <- 0

pred <- list(x=unique(pred$X1),y=unique(pred$X2),z=matrix(pred$f,nrow=length(unique(pred$X1)),byrow = TRUE),col=matrix(0,nrow=length(unique(pred$X1))))


df <- rbind(train,tst)




fig <- plot_ly()
fig <- fig %>% add_trace(type="scatter3d",data=df, x = ~X1, y = ~X2, z = ~f, color = ~id, colors = c('#BF382A', "grey" ,'black'),showlegend=T)
fig <- fig %>% add_trace(type="surface",data=pred,x=~x,y=~y,z=~z,opacity=0.5,surfacecolor=~col,showlegend=F)
fig <- fig %>% layout(scene = list(xaxis = list(title = ''),
                     yaxis = list(title = ''),
                     zaxis = list(title = 'fitness'),
                     camera=list(eye = list(x=-1.5, y=1, z=0.64))))
fig


```


```{r}

library(plotly)
psize <- 10
set.seed(4)
pts <- data.frame(cbind(sample(1:psize,20,replace=T),sample(1:psize,20,replace=T)))
pts <- unique(pts)
pk1 <- c(2,2)
pk2 <- c(7,8)

pts$f <- apply(pts,1,function(pki){
  max(1/(1+sqrt(sum((pki-pk1)^2))),1/(1+0.7*sqrt(sum((pki-pk2)^2))))
})


library(fields)

opt <- Krig(pts[,1:2],pts$f,m=1,df=nrow(pts)-3)
pred <- expand.grid(0:(1+psize),0:(1+psize))
colnames(pred) <- c("X1","X2")
pred$f <- predict(opt,pred)
pred$col <- 0

pred <- list(x=unique(pred$X1),y=unique(pred$X2),z=matrix(pred$f,nrow=length(unique(pred$X1)),byrow = TRUE),col=matrix(0,nrow=length(unique(pred$X1))))







fig <- plot_ly(colors="grey")
fig <- fig %>% add_trace(type="surface",data=pred,x=~x,y=~y,z=~z,opacity=1,surfacecolor=~col,showlegend=F)
fig <- fig %>% layout(scene = list(xaxis = list(title = ''),
                     yaxis = list(title = ''),
                     zaxis = list(title = 'fitness'),
                     camera=list(eye = list(x=-1.5, y=1, z=0.64))))
fig




```